# Full Goblocks config example with all available block types and options.

# Each block must have a block_index field indicating the blocks position.
# block_index values must start with 1 and be sequential.

# Each block must have an update_interval field indicating the time interval in
# seconds to update the block. Note that this interval does not affect the
# refresh rate of Goblocks; it only impactes the timing in which a block's info
# gets updated.

raid:
    block_index: 1
    update_interval: 1

disk:
    block_index: 2
    update_interval: 1

load:
    block_index: 3
    update_interval: 1
    crit_load: 4

memory:
    block_index: 4
    update_interval: 1
    crit_mem: 1

# Some block types can have multiple instances, which are specified in a YAML
# array.

temperatures:
    - block_index: 5
      update_interval: 1
      cpu_temp_path: /sys/devices/platform/coretemp.0/hwmon/hwmon1
      crit_temp: 50

interfaces:
    - block_index: 6
      update_interval: 1
      interface_name: enp3s0

    - block_index: 7
      update_interval: 1
      interface_name: wlp4s2

# If a block has an update_signal field, then that block will be updated and
# Goblocks refreshed when Goblocks receives an RTMIN signal offset by the given
# signal number.
# For example, if update_signal is 1, then running 'pkill -RTMIN+1 goblocks'
# will cause Goblocks to update the block and refresh.
# The update_signal value must be 1 or greater.

volume:
    block_index: 8
    update_interval: 60
    update_signal: 8

# The time_format value must be a string in Go's standard time format (see
# https://golang.org/pkg/time/#pkg-constants).

time:
    block_index: 9
    update_interval: 1
    time_format: 2006-01-02 15:04
